name: Code PushUp
description: Quality metrics from Code PushUp

branding:
  icon: activity
  color: blue

inputs:
  monorepo:
    description: |
      For repos containing multiple projects. Options are:

      - `false`: single project mode (default)
      - `true`: turns on monorepo mode (autodetects tool unless `projects` is specified)
      - `nx`: Nx workspace
      - `turbo`: Turborepo
      - `npm`: NPM workspaces
      - `yarn`: Yarn workspaces
      - `pnpm`: PNPM workspaces
    required: true
    default: false
  parallel:
    description: |
      Configures parallel execution in monorepo mode. Possibly values are:

      - `false`: sequential (default)
      - `true`: parallel with default number of jobs (depends on monorepo tool)
      - integer which sets the number of concurrent jobs
    required: true
    default: false
  projects:
    description: |
      Project folders for custom monorepo setup.

      Only used when `monorepo: true` is set and no known monorepo tool is detected.
      Should be a comma-separated list of project folders (supports globs).
    required: false
  task:
    description: |
      Name of task for running Code PushUp CLI in monorepo mode. Defaults to `code-pushup`.

      Depending on what monorepo tool is being used, this task may represent a `package.json` script, binary executable, Nx target or Turbo task.
    required: true
    default: code-pushup
  nxProjectsFilter:
    description: |
      CLI arguments for `nx show projects` used to list Nx projects in monorepo mode. Replaces `{task}` with `task` input.
    required: true
    default: --with-target={task}
  bin:
    description: Custom code-pushup executable
    required: true
    default: npx --no-install code-pushup
  config:
    description: Custom code-pushup.config path
    required: false
  directory:
    description: Custom working directory
    required: false
  silent:
    description: Silence logs from Code Pushup CLI
    required: true
    default: false
  token:
    description: GITHUB_TOKEN or a repo scoped PAT
    required: true
    default: ${{ github.token }}
  artifacts:
    description: Upload/download artifacts for caching code-pushup reports
    required: true
    default: true
  retention:
    description: Artifact retention period in days
    required: false
  annotations:
    description: Create file annotations in GitHub
    required: true
    default: true

outputs:
  artifact-id:
    description: ID of uploaded report artifact
  comment-id:
    description: ID of created or updated GitHub comment

runs:
  using: 'node20' # TODO: update the runner to node22 as soon as it is supported https://github.com/actions/runner/issues/3600
  main: dist/index.js
