name: Code PushUp
description: Quality metrics from Code PushUp
author: code-pushup

branding:
  icon: activity
  color: blue

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
