name: Code PushUp
description: Quality metrics from Code PushUp

branding:
  icon: activity
  color: blue

inputs:
  bin:
    description: Custom code-pushup executable
    required: true
    default: npx --no-install code-pushup
  config:
    description: Custom code-pushup.config path
    required: false
  directory:
    description: Custom working directory
    required: false
  silent:
    description: Silence logs from Code Pushup CLI
    required: true
    default: false
  token:
    description: GITHUB_TOKEN or a repo scoped PAT
    required: true
    default: ${{ github.token }}
  artifacts:
    description: Upload/download artifacts for caching code-pushup reports
    required: true
    default: true
  retention:
    description: Artifact retention period in days
    required: false

outputs:
  artifact-id:
    description: ID of uploaded report artifact
  comment-id:
    description: ID of created or updated GitHub comment

runs:
  using: node20
  main: dist/index.js
